### ISSUE TITLE
관리자에서 새소식 항목 수 저정

### ISSUE THREAD

**Issue by akasima** [xpressengine/plugin-news_client#1]
지금 시점에서 11개 나오고 있는데 최근 공지만 보면 될것같습니다.

5개 정도면 보여주면 되지 않을까요?

![2017-03-28 2 48 24](https://cloud.githubusercontent.com/assets/5836237/24390727/c8ac931c-13c5-11e7-880d-be504fab0cd0.png)

**Comment by jhyeon1010** [comment]
news 서버 쪽에서 처리하였습니다.
